apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantumgate-deployment
  namespace: quantumgate
  labels:
    app: quantumgate
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quantumgate
  template:
    metadata:
      labels:
        app: quantumgate
        version: v1.0.0
    spec:
      containers:
      - name: quantumgate
        image: quantumgate:latest
        ports:
        - containerPort: 80
        - containerPort: 8001
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: quantumgate-secrets
              key: mongo-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: quantumgate-secrets
              key: secret-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: quantumgate-secrets
              key: openai-api-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: quantumgate-secrets
              key: anthropic-api-key
        - name: ETHEREUM_RPC_URL
          valueFrom:
            secretKeyRef:
              name: quantumgate-secrets
              key: ethereum-rpc-url
        - name: DEBUG
          value: "false"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: logs-volume
          mountPath: /var/log
      volumes:
      - name: config-volume
        configMap:
          name: quantumgate-config
      - name: logs-volume
        emptyDir: {}
      imagePullSecrets:
      - name: quantumgate-registry-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quantumgate-config
  namespace: quantumgate
data:
  app.conf: |
    [app]
    name = QuantumGate
    version = 1.0.0
    environment = production
    
    [encryption]
    kyber_variant = kyber1024
    dilithium_variant = dilithium3
    
    [ai]
    threat_threshold = 0.8
    model_update_interval = 3600
    
    [blockchain]
    default_network = ethereum
    gas_limit = 21000
---
apiVersion: v1
kind: Secret
metadata:
  name: quantumgate-secrets
  namespace: quantumgate
type: Opaque
data:
  mongo-url: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNw==  # mongodb://mongodb-service:27017
  secret-key: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # your-super-secret-key-change-in-production
  openai-api-key: ""  # Base64 encoded OpenAI API key
  anthropic-api-key: ""  # Base64 encoded Anthropic API key
  ethereum-rpc-url: ""  # Base64 encoded Ethereum RPC URL